openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - type: string
        name: userId
        in: path
        required: true
    get:
      summary: Get User
      tags: []
      responses: {}
      description: ''
components:
  schemas: {}
