openapi: 3.0.0
info:
  title: Users
  version: '1.0'
servers:
  - url: 'https://api.dev.icheck.vn/api/v1'
paths:
  '/users/{userId}':
    parameters:
      - type: string
        name: userId
        in: path
        required: true
    get:
      summary: Get User
      tags: []
      responses: {}
      description: Lấy thông tin người dùng
      parameters: []
  /users:
    get:
      summary: List All Users
      tags: []
      responses: {}
      description: ''
components:
  schemas: {}
