openapi: 3.0.0
info:
  title: Vouchers
  version: '1.0'
servers:
  - url: 'http://localhost:3000/api/v1'
paths:
  /vouchers:
    get:
      summary: Lấy danh sách Vouchers
      tags:
        - Vouchers
      requestBody: {}
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  rows:
                    type: array
                    items:
                      $ref: ./models/voucheresponse.v1.yaml
                  count:
                    type: integer
              examples: {}
      parameters:
        - schema:
            type: integer
          in: query
          name: limit
          description: ''
          required: true
        - schema:
            type: integer
          in: query
          name: offset
          required: true
        - schema:
            type: string
          in: query
          name: order
          description: 'Sắp xếp (VD: id hoặc -id)'
        - schema:
            type: string
          in: query
          name: search
          description: Tìm kiếm theo tên hoặc mã
        - schema:
            type: string
            enum:
              - discount
              - refund
          in: query
          name: type
          description: Loại voucher
        - schema:
            type: string
            enum:
              - public
              - private
              - individual
          in: query
          name: display
          description: Kiểu hiển thị
        - schema:
            type: string
            enum:
              - waiting
              - verifyed
              - cancel
          in: query
          name: verifyed
          description: Trạng thái voucher
        - schema:
            type: string
            enum:
              - scheduled
              - ongoing
              - finished
          in: query
          name: state
          description: Tình trạng voucher
        - schema:
            type: number
          in: query
          name: shop_id
          description: ID của shop
        - schema:
            type: string
          in: query
          name: from_at
          description: 'Khoảng thời gian bắt đầu (VD: "2019-09-11T07:54:14.414Z,2019-10-13T07:54:14.414Z")'
        - schema:
            type: string
          in: query
          name: to_at
          description: 'Khoảng thời gian kết thúc (VD: "2019-09-11T07:54:14.414Z,2019-10-13T07:54:14.414Z")'
    post:
      summary: Tạo Voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/voucheresponse.v1.yaml
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/vouchercreate.v1.yaml
      tags:
        - Vouchers
  '/vouchers/{id}':
    get:
      summary: Thông tin chi tiết voucher
      tags:
        - Vouchers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/voucheresponse.v1.yaml
      description: ''
    parameters:
      - schema:
          type: integer
        name: id
        in: path
        required: true
    put:
      summary: Cập thật thông tin voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/voucheresponse.v1.yaml
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/voucherupdate.v1.yaml
      tags:
        - Vouchers
    delete:
      summary: Xóa voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/voucheresponse.v1.yaml
      description: ''
      tags:
        - Vouchers
  /vouchers/cancel-verify:
    parameters: []
    post:
      summary: Hủy xác thực Vouchers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
      tags:
        - Vouchers
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                verify_reject_reason:
                  type: string
                  description: lý do hủy duyệt
                ids:
                  type: array
                  description: danh sách id voucher
                  items:
                    type: number
              required:
                - verify_reject_reason
                - ids
          application/xml:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: number
        description: ''
  /vouchers/verify:
    parameters: []
    post:
      summary: Xác thực vouchers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: number
      tags:
        - Vouchers
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                ids:
                  type: array
                  items:
                    type: number
              required:
                - ids
  /voucher-users:
    get:
      summary: Danh sách voucher được user sưu tầm
      tags:
        - voucher_users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  rows:
                    type: array
                    items:
                      $ref: ./models/voucheruserresponse.v1.yaml
                  count:
                    type: number
      description: Lấy ra danh sách các voucher đã được user sưu tầm
      parameters:
        - schema:
            type: number
          in: query
          name: limit
          required: true
          description: ''
        - schema:
            type: number
          in: query
          name: offset
          required: true
        - schema:
            type: string
          in: query
          name: order
        - schema:
            type: number
          in: query
          name: voucher_id
          description: id của voucher
        - schema:
            type: number
          in: query
          name: user_id
          description: id của user sưu tầm voucher
        - schema:
            type: string
          in: query
          name: search
          description: tìm kiếm mã voucher
    post:
      summary: Nhận mã vouchers
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: ./models/voucheruserresponse.v1.yaml
      tags:
        - voucher_users
      description: Api giúp user sưu tầm 1 hoặc nhiều mã voucher
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./models/voucherusercreate.v1.yaml
  /voucher-list-insights:
    get:
      summary: Thống kê số voucher
      tags:
        - voucher_list_insights
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: ./models/voucherlistinsightresponse.v1.yaml
      parameters:
        - schema:
            type: string
          in: query
          name: search
          description: Tìm kiếm theo tên hoặc mã
        - schema:
            type: string
            enum:
              - discount
              - refund
          in: query
          name: type
          description: Loại voucher
        - schema:
            type: string
            enum:
              - public
              - private
              - individual
          in: query
          name: display
          description: Kiểu hiển thị
        - schema:
            type: string
            enum:
              - waiting
              - verifyed
              - cancel
          in: query
          name: verifyed
          description: Trạng thái voucher
        - schema:
            type: string
            enum:
              - scheduled
              - ongoing
              - finished
          in: query
          name: state
          description: Tình trạng voucher
        - schema:
            type: number
          in: query
          name: shop_id
          description: ID của shop
        - schema:
            type: string
          in: query
          name: from_at
          description: 'Khoảng thời gian bắt đầu (VD: "2019-09-11T07:54:14.414Z,2019-10-13T07:54:14.414Z")'
        - schema:
            type: string
          in: query
          name: to_at
          description: 'Khoảng thời gian kết thúc (VD: "2019-09-11T07:54:14.414Z,2019-10-13T07:54:14.414Z")'
    parameters: []
components:
  schemas: {}
as: {}
